services:
  frontend:
    image: nginx:stable
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../certificate/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ../../certificate/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - backend
    networks:
      - voiture-rc-network
    restart: unless-stopped

  backend:
    image: node:16-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "50902:50902"
      - "50903:50903"
    command: sh -c "npm install && node app.js"
    networks:
      - voiture-rc-network
    restart: unless-stopped

networks:
  voiture-rc-network:
    driver: bridge